export const LISTING_LIST_REQUEST = 'LISTING_LIST_REQUEST'
export const LISTING_LIST_SUCCESS = 'LISTING_LIST_SUCCESS'
export const LISTING_LIST_FAIL = 'LISTING_LIST_FAIL'

export const LISTING_DETAILS_REQUEST = 'LISTING_DETAILS_REQUEST'
export const LISTING_DETAILS_SUCCESS = 'LISTING_DETAILS_SUCCESS'
export const LISTING_DETAILS_FAIL = 'LISTING_DETAILS_FAIL'

export const LISTING_CREATE_REQUEST = 'LISTING_CREATE_REQUEST'
export const LISTING_CREATE_SUCCESS = 'LISTING_CREATE_SUCCESS'
export const LISTING_CREATE_FAIL = 'LISTING_CREATE_FAIL'

export const LISTING_CLEAR = 'LISTING_CLEAR'
